run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters-settings:
  govet:
    enable-all: false
    enable:
      - asmdecl
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - fieldalignment  # Disabled: memory optimization not critical
      - shadow  # Disabled: variable shadowing is common Go pattern
  gocyclo:
    # Increase complexity threshold for CLI command functions
    min-complexity: 30
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/jasongoecke/go-veo3

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocyclo
    - unparam
    - gosec
  disable:
    - misspell  # Disabled: British vs American English spelling (Cancelled vs Canceled)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
