package cli

import (
	"context"
	"fmt"

	"github.com/jasongoecke/go-veo3/pkg/config"
	"github.com/jasongoecke/go-veo3/pkg/veo3"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// newExtendCmd creates the extend command
func newExtendCmd() *cobra.Command {
	// Create fresh command instance to avoid flag redefinition in tests
	extendCmd := &cobra.Command{
		Use:   "extend [video-path]",
		Short: "Extend an existing Veo-generated video",
		Long: `Extend an existing Veo-generated video by up to 7 seconds.

This command takes a Veo-generated video file and extends it with additional
content. The extension can be guided by an optional prompt to specify what
should happen in the extended portion.

Supported video format: MP4
Maximum input video duration: 141 seconds
Maximum extension: 7 seconds (chainable for longer videos)
The input video must be generated by Veo (validated by metadata).`,
		Example: `  # Extend video with default settings
  veo3 extend video.mp4

  # Extend with specific prompt for continuation
  veo3 extend video.mp4 --prompt "Continue with dramatic action sequence"

  # Extend and save to specific directory
  veo3 extend video.mp4 --prompt "Fade to sunset" --output ./extended/

  # Chain extensions for longer videos
  veo3 extend video.mp4 --prompt "Part 2" --filename part2.mp4
  veo3 extend part2.mp4 --prompt "Part 3" --filename part3.mp4`,
		Args: cobra.ExactArgs(1),
		RunE: runExtend,
	}

	// Add flags
	extendCmd.Flags().StringP("prompt", "p", "", "Extension prompt (what should happen in the extended portion)")
	extendCmd.Flags().StringP("model", "m", "", "Model to use (must support video extension)")
	extendCmd.Flags().String("output", "", "Output directory for downloaded video")
	extendCmd.Flags().String("filename", "", "Custom filename for output video")
	extendCmd.Flags().Bool("no-wait", false, "Start extension and return immediately")
	extendCmd.Flags().Bool("no-download", false, "Skip automatic video download")
	extendCmd.Flags().Bool("pretty", false, "Pretty-print JSON output (with --json)")

	// Note: Resolution, duration, and aspect ratio are inherited from the input video
	// They are not configurable for extensions

	// Bind flags to viper for config integration
	viper.BindPFlag("model", extendCmd.Flags().Lookup("model"))
	viper.BindPFlag("output", extendCmd.Flags().Lookup("output"))

	return extendCmd
}

// runExtend handles video extension
func runExtend(cmd *cobra.Command, args []string) error {
	videoPath := args[0]

	// Load configuration using manager
	manager := config.NewManager("")
	cfg, err := manager.Load()
	if err != nil {
		// Use defaults if config load fails
		cfg = &config.Configuration{
			DefaultModel:        config.DefaultModel,
			OutputDirectory:     ".",
			PollIntervalSeconds: config.DefaultPollInterval,
		}
	}

	// Get flag values with config fallbacks
	prompt, _ := cmd.Flags().GetString("prompt")
	model := getStringWithDefault(cmd, "model", cfg.DefaultModel)
	outputDir := getStringWithDefault(cmd, "output", cfg.OutputDirectory)
	filename, _ := cmd.Flags().GetString("filename")
	noWait, _ := cmd.Flags().GetBool("no-wait")
	noDownload, _ := cmd.Flags().GetBool("no-download")
	jsonFormat := viper.GetBool("json")
	pretty, _ := cmd.Flags().GetBool("pretty")

	// Create extension request
	request := &veo3.ExtensionRequest{
		VideoPath:       videoPath,
		ExtensionPrompt: prompt,
		Model:           model,
	}

	// Validate request
	if err := request.Validate(); err != nil {
		return handleError(err, jsonFormat, pretty)
	}

	// Create API client
	apiKey := viper.GetString("api-key")
	if apiKey == "" {
		apiKey = cfg.APIKey
	}

	client, err := veo3.NewClient(context.Background(), apiKey)
	if err != nil {
		return handleError(err, jsonFormat, pretty)
	}

	// Show upload progress for video
	if !jsonFormat {
		fmt.Printf("⬆ Uploading video: %s\n", videoPath)

		// Get video info for display
		videoInfo, err := veo3.GetVideoInfo(videoPath)
		if err == nil {
			sizeMB := float64(videoInfo.SizeBytes) / (1024 * 1024)
			fmt.Printf("🎬 %s (%.1f MB)\n", videoInfo.Format, sizeMB)
		}
	}

	// Submit extension request
	ctx := context.Background()
	operation, err := client.ExtendVideo(ctx, request)
	if err != nil {
		return handleError(err, jsonFormat, pretty)
	}

	// Handle async mode
	if noWait {
		return outputOperation(operation, jsonFormat, pretty)
	}

	// Poll for completion with progress display
	if !jsonFormat {
		fmt.Printf("➕ Extending video... (Operation: %s)\n", operation.ID)
	}

	operation, err = pollOperation(ctx, client, operation.ID, jsonFormat)
	if err != nil {
		return handleError(err, jsonFormat, pretty)
	}

	// Download video if completed and not disabled
	if operation.Status == veo3.StatusDone && !noDownload {
		if !jsonFormat {
			fmt.Println("✓ Video extension completed!")
		}

		err = downloadVideo(ctx, operation, outputDir, filename, jsonFormat)
		if err != nil {
			return handleError(err, jsonFormat, pretty)
		}
	}

	return outputOperation(operation, jsonFormat, pretty)
}
